apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: ws_events
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
    version: 1 